apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - name: meu-pvc
        mountPath: /usr/share/nginx/html
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
  volumes:
    - name: meu-pvc
      persistentVolumeClaim:
        claimName: meu-pvc
