// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViewComponentSite.Infrastrucuture.Persistence;

#nullable disable

namespace ViewComponentSite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("ViewComponentSite.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Eletrônicos e Eletrodomésticos",
                            Name = "Eletrônicos"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Higiene e limpeza em geral",
                            Name = "Limpeza"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Estética e beleza",
                            Name = "Cosméticos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
